// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package com.zsaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static com.zsaltedfish.aria2.global.Aria2.*;

@Name("std::vector<std::vector<std::string> >") @Properties(inherit = com.zsaltedfish.aria2.prest.Aria2.class)
public class StringVectorVector extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public StringVectorVector(Pointer p) { super(p); }
    public StringVectorVector(StringVector value) { this(1); put(0, value); }
    public StringVectorVector(StringVector ... array) { this(array.length); put(array); }
    public StringVectorVector()       { allocate();  }
    public StringVectorVector(long n) { allocate(n); }
    private native void allocate();
    private native void allocate(@Cast("size_t") long n);
    public native @Name("operator =") @ByRef StringVectorVector put(@ByRef StringVectorVector x);

    public boolean empty() { return size() == 0; }
    public native long size();
    public void clear() { resize(0); }
    public native void resize(@Cast("size_t") long n);

    @Index(function = "at") public native @ByRef StringVector get(@Cast("size_t") long i);
    public native StringVectorVector put(@Cast("size_t") long i, StringVector value);

    public native @ByVal Iterator insert(@ByVal Iterator pos, @ByRef StringVector value);
    public native @ByVal Iterator erase(@ByVal Iterator pos);
    public native @ByVal Iterator begin();
    public native @ByVal Iterator end();
    @NoOffset @Name("iterator") public static class Iterator extends Pointer {
        public Iterator(Pointer p) { super(p); }
        public Iterator() { }

        public native @Name("operator ++") @ByRef Iterator increment();
        public native @Name("operator ==") boolean equals(@ByRef Iterator it);
        public native @Name("operator *") @ByRef @Const StringVector get();
    }

    public StringVector[] get() {
        StringVector[] array = new StringVector[size() < Integer.MAX_VALUE ? (int)size() : Integer.MAX_VALUE];
        for (int i = 0; i < array.length; i++) {
            array[i] = get(i);
        }
        return array;
    }
    @Override public String toString() {
        return java.util.Arrays.toString(get());
    }

    public StringVector pop_back() {
        long size = size();
        StringVector value = get(size - 1);
        resize(size - 1);
        return value;
    }
    public StringVectorVector push_back(StringVector value) {
        long size = size();
        resize(size + 1);
        return put(size, value);
    }
    public StringVectorVector put(StringVector value) {
        if (size() != 1) { resize(1); }
        return put(0, value);
    }
    public StringVectorVector put(StringVector ... array) {
        if (size() != array.length) { resize(array.length); }
        for (int i = 0; i < array.length; i++) {
            put(i, array[i]);
        }
        return this;
    }
}

