// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package com.zsaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static com.zsaltedfish.aria2.global.Aria2.*;


/**
 * \struct
 *
 * This object contains URI and its status.
 */
@Namespace("aria2") @Properties(inherit = com.zsaltedfish.aria2.prest.Aria2.class)
public class UriData extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public UriData() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public UriData(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public UriData(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public UriData position(long position) {
        return (UriData)super.position(position);
    }
    @Override public UriData getPointer(long i) {
        return new UriData((Pointer)this).offsetAddress(i);
    }

  /**
   * URI
   */
  public native @StdString BytePointer uri(); public native UriData uri(BytePointer setter);
  /**
   * The status of URI
   */
  public native @Cast("aria2::UriStatus") int status(); public native UriData status(int setter);
}
