// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package io.github.ssaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static io.github.ssaltedfish.aria2.global.Aria2.*;


/**
 * \functypedef
 *
 * Callback function invoked when download event occurred. The |event|
 * indicates the event. See :type:{@code DownloadEvent} for events. The
 * |gid| refers to the download which this event was fired on. The
 * |userData| is a pointer specified in
 * :member:{@code SessionConfig::userData}.
 *
 * At the moment, the return value is ignored, but the implementation
 * of this callback should return 0 for compatibility.
 */
@Properties(inherit = io.github.ssaltedfish.aria2.prest.Aria2.class)
public class DownloadEventCallback extends FunctionPointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public    DownloadEventCallback(Pointer p) { super(p); }
    protected DownloadEventCallback() { allocate(); }
    private native void allocate();
    public native int call(Session session, DownloadEvent event,
                                     @Cast("aria2::A2Gid") long gid, Pointer userData);
}
