// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package io.github.ssaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static io.github.ssaltedfish.aria2.global.Aria2.*;


/**
 * \struct
 *
 * Global statistics of current aria2 session.
 */
@Namespace("aria2") @Properties(inherit = io.github.ssaltedfish.aria2.prest.Aria2.class)
public class GlobalStat extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public GlobalStat() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public GlobalStat(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public GlobalStat(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public GlobalStat position(long position) {
        return (GlobalStat)super.position(position);
    }
    @Override public GlobalStat getPointer(long i) {
        return new GlobalStat((Pointer)this).offsetAddress(i);
    }

  /**
   * Overall download speed (byte/sec).
   */
  public native int downloadSpeed(); public native GlobalStat downloadSpeed(int setter);
  /**
   * Overall upload speed(byte/sec).
   */
  public native int uploadSpeed(); public native GlobalStat uploadSpeed(int setter);
  /**
   * The number of active downloads.
   */
  public native int numActive(); public native GlobalStat numActive(int setter);
  /**
   * The number of waiting downloads.
   */
  public native int numWaiting(); public native GlobalStat numWaiting(int setter);
  /**
   * The number of stopped downloads.
   */
  public native int numStopped(); public native GlobalStat numStopped(int setter);
}
