// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package io.github.ssaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static io.github.ssaltedfish.aria2.global.Aria2.*;


/**
 * \struct
 *
 * BitTorrent metainfo data retrieved from ".torrent" file.
 */
@Namespace("aria2") @Properties(inherit = io.github.ssaltedfish.aria2.prest.Aria2.class)
public class BtMetaInfoData extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public BtMetaInfoData() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public BtMetaInfoData(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public BtMetaInfoData(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public BtMetaInfoData position(long position) {
        return (BtMetaInfoData)super.position(position);
    }
    @Override public BtMetaInfoData getPointer(long i) {
        return new BtMetaInfoData((Pointer)this).offsetAddress(i);
    }

  /**
   * List of lists of announce URI. If ".torrent" file contains
   * {@code }announce{@code } and no {@code }announce-list{@code }, {@code }announce{@code } is converted
   * to {@code }announce-list{@code } format.
   */
  public native @ByRef StringVectorVector announceList(); public native BtMetaInfoData announceList(StringVectorVector setter);
  /**
   * {@code }comment{@code } for the torrent. {@code }comment.utf-8{@code } is used if
   * available.
   */
  public native @StdString BytePointer comment(); public native BtMetaInfoData comment(BytePointer setter);
  /**
   * The creation time of the torrent. The value is an integer since
   * the Epoch, measured in seconds.
   */
  public native @ByRef @Cast("time_t*") Pointer creationDate(); public native BtMetaInfoData creationDate(Pointer setter);
  /**
   * File mode of the torrent.
   */
  public native @Cast("aria2::BtFileMode") int mode(); public native BtMetaInfoData mode(int setter);
  /**
   * {@code }name{@code } in {@code }info{@code } dictionary. {@code }name.utf-8{@code } is used if
   * available.
   */
  public native @StdString BytePointer name(); public native BtMetaInfoData name(BytePointer setter);
}
