// Targeted by JavaCPP version 1.5.7: DO NOT EDIT THIS FILE

package io.github.ssaltedfish.aria2.cpp;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static org.bytedeco.javacpp.presets.javacpp.*;

import static io.github.ssaltedfish.aria2.global.Aria2.*;

@Name("std::vector<FileData>") @Properties(inherit = io.github.ssaltedfish.aria2.prest.Aria2.class)
public class FileDataVector extends Pointer {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public FileDataVector(Pointer p) { super(p); }
    public FileDataVector(FileData value) { this(1); put(0, value); }
    public FileDataVector(FileData ... array) { this(array.length); put(array); }
    public FileDataVector()       { allocate();  }
    public FileDataVector(long n) { allocate(n); }
    private native void allocate();
    private native void allocate(@Cast("size_t") long n);
    public native @Name("operator =") @ByRef FileDataVector put(@ByRef FileDataVector x);

    public native boolean empty();
    public native long size();
    public native void clear();
    public native void resize(@Cast("size_t") long n);

    @Index(function = "at") public native @ByRef FileData get(@Cast("size_t") long i);
    public native FileDataVector put(@Cast("size_t") long i, FileData value);

    public native @ByVal Iterator insert(@ByVal Iterator pos, @ByRef FileData value);
    public native @ByVal Iterator erase(@ByVal Iterator pos);
    public native @ByVal Iterator begin();
    public native @ByVal Iterator end();
    @NoOffset @Name("iterator") public static class Iterator extends Pointer {
        public Iterator(Pointer p) { super(p); }
        public Iterator() { }

        public native @Name("operator ++") @ByRef Iterator increment();
        public native @Name("operator ==") boolean equals(@ByRef Iterator it);
        public native @Name("operator *") @ByRef @Const FileData get();
    }

    public FileData[] get() {
        FileData[] array = new FileData[size() < Integer.MAX_VALUE ? (int)size() : Integer.MAX_VALUE];
        for (int i = 0; i < array.length; i++) {
            array[i] = get(i);
        }
        return array;
    }
    @Override public String toString() {
        return java.util.Arrays.toString(get());
    }

    @Name("pop_back")
    public native void popBack();

    @Name("push_back")
    public native void pushBack(@ByRef FileData value);


    private FileDataVector put(FileData ... array) {
        if (size() != array.length) { resize(array.length); }
        for (int i = 0; i < array.length; i++) {
            put(i, array[i]);
        }
        return this;
    }
}

